### PR TITLE
Adding OneTouch features

### PR DESCRIPTION
**Pull request by josh-authy**
send_approval_request && check_approval_status API calls.
OneTouch documentation.
Adding tests.

### CODE REVIEW

**Comment by josh-authy** [comment]
Is this repo dead?

**Comment by DanielBarnes** [comment]
@josh-authy would you like to added to the repo to maintain it? Reach out to @evilpacket or I can for you. I believe neither of us are very active on this repo.

I'll merge your request but am not able to update the package on npm at this time.

**Comment by evilpacket** [comment]
@josh-authy happy to add you as a maintainer and give access on npm so that you can push updated code.

**Comment by josh-authy** [comment]
@evilpacket Lets have a conversation about this.  Can you reach out to me @ josh [at] twilio.

**Pull request merged**
